****IMPORT & MERGE DOFILE*****
**Author: Caton Brewster, Dean Team RA
**Date created: 12/7/2015

/*
Purpose: This dofile imports the weekly CHCI sheet we receive with Access data and 
merges them with one another. Some formatting is done between merges to ensure compatability. 
The final dataset that is saved HAS PII AND MUST REMAIN ENCRYPTED. The weekly sheets
we receive are running lists of participants. 
*/

clear
set more off
set maxvar 32767	// Stata's max var limit
//vers 12			//uncomment this if need to run for those using stata v12

tempfile access baseline dashboard noshows stickK
***************************************************
**1. Set Globals
***************************************************
c data
do dofiles/1_globals.do

***************************************************
**2. Import Data annd prep it 
***************************************************

**A. Access**********************************

import excel "$CHCIdta\Access\C2Q Patients $date.xlsx", sheet("C2Q_Patients") firstrow

//save raw version of sheets
save  "$rawdtaPII/CHCI/Access/RawAccess_$date", replace	
order StudyIDNumber ControlNumber

//prep data to merge
rename * a_*
rename a_StudyIDNumber StudyID
rename a_ControlNumber ChartNumber 

tostring ChartNumber StudyID, replace

save `access'

**B. Baseline Survey **********************************

import excel "$CHCIdta\BaselineSurvey\Data_all_151205.xls", sheet("Sheet1") firstrow clear

//save raw version of sheets
save  "$rawdtaPII/CHCI/Baseline/RawBaseline_$date", replace	

//prep data to merge
rename * b_*
rename b_StudyID StudyID
rename b_ChartNumber ChartNumber 

tostring ChartNumber StudyID, replace
drop if StudyID == "Open-Ended Response" 	//this is the row in the data that is auto-generated by SurveyMonkey

save `baseline'

/*
**C. Dashboard **********************************

import excel "$CHCIdta\Dashboard\*********$date.xls", sheet("Sheet1") firstrow clear

//save raw version of sheets
save  "$rawdtaPII/CHCI/Dashboard/RawDashboard_$date", replace	

save `dashboard'

**C. No Show Data **********************************

import excel "$CHCIdta\NoShows\*********$date.xls", sheet("Sheet1") firstrow clear

//save raw version of sheets
save  "$rawdtaPII/CHCI/NoShows/RawNoShows_$date", replace	

save `noshows'

**C. Endline**********************************

import excel "$CHCIdta\Endline\*********$date.xls", sheet("Sheet1") firstrow clear

//save raw version of sheets
save  "$rawdtaPII/CHCI/Endline/RawEndline_$date", replace	

save `endline'
*/

***************************************************
**3. Merge Data
***************************************************

use `access', clear

**Access with Baseline
merge 1:m StudyID ChartNumber using `baseline' 
//assert _merge!= 2 
//br if _merge == 2	
drop if _merge == 2			//be sure to look at data first if assertion is false
assert _merge!= 1
//br if _merge == 1	
drop if _merge == 1			//be sure to look at data first if assertion is false
drop _merge

**Check for inconsistencies in mutual variables
//baseline has rows for email address and first/last name. We don't ask this. Drop them. 
drop b_EmailAddress b_FirstName b_LastName

assert StudyID == b_ReenterStudyID
assert ChartNumber == b_ReenterChartNumber

***************************************************
**3. Save raw data with PII 
***************************************************

save "$rawdtaPII/merged/1_reformatted/reformatted_raw_merged_$date", replace	
